### ISSUE TITLE
[BUG] Reportory as Ressource Path

### ISSUE THREAD

**Issue by QuentinRa** [lgs-games/tyrn#18]
**Describe the bug and what you expected**
A repertory can be selected as a ressources path, it's shown but there is a NullPointerException on submit.

```java
TyrnExceptionHandler#manageError
null
java.lang.NullPointerException
	at tyrn.api.sql.SQLRequestAPI.updateCategoryElement(SQLRequestAPI.java:579)
	at tyrn.api.TyrnAPIFile.updateCategoryElement(TyrnAPIFile.java:302)
	at tyrn.ui.lib.element.ElementsBase$SubmitElement.actionPerformed(ElementsBase.java:175)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
```

**Comment by QuentinRa** [comment]
fixed in 6406752
